# Generated by Django 6.0.6 on 2026-09-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Διαχειριστής'), ('courier', 'Courier')], default='admin', help_text='Admins see the full panel. Couriers only see Παραδόσεις.', max_length=20),
        ),
    ]
