# Generated by Django 6.0.6 on 2026-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='floor',
            field=models.CharField(blank=True, default='', help_text="Delivery floor (e.g. 'Ισόγειο', '3ος'). Filled in during checkout.", max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude of the delivery address pin, set via Google Maps at checkout.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude of the delivery address pin, set via Google Maps at checkout.', max_digits=9, null=True),
        ),
    ]
