# Generated by Django 6.0.6 on 2026-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_phone_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Greek mobile (69XXXXXXXX). Required at signup; optional until then on legacy accounts.', max_length=20),
        ),
    ]
