"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local secrets from .env (gitignored). See .env.example for required keys.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ac3v7p+%56#4x_ds_nw5fyy=igyxg$&2e%ew!#76$!uz0%m^f)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # required by allauth

    # Authentication (custom user + social login)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    # Local apps
    'products',
    'accounts',
    'orders',
    'cart',
    'checkout',
    'newsletter',
    'wishlist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # Needed for Django admin login and standard email/password auth.
    'django.contrib.auth.backends.ModelBackend',
    # Needed for allauth's own authentication flows (incl. social login).
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'newsletter.context_processors.recaptcha',
                'products.context_processors.nav_state',
                'cart.context_processors.cart_state',
                'accounts.context_processors.auth_helpers',
                'wishlist.context_processors.wishlist_state',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'accounts.password_validators.PasswordHasDigitValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Project-level static files (design assets shared across templates - logos,
# hand-extracted background/design tokens from the site mockup, etc.), as
# opposed to `media/` which holds user/admin-uploaded content (product
# photos). Needed because these files don't belong to any single app.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (user-uploaded content, e.g. product and category images)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model
# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/

AUTH_USER_MODEL = 'accounts.CustomUser'


# django-allauth configuration
# https://docs.allauth.org/en/latest/account/configuration.html

# Log in with email + password only (no separate username field at all).
ACCOUNT_LOGIN_METHODS = {'email'}
# Registration only asks for email + password (entered twice for confirmation).
# All other customer details (phone, city, address, etc.) are collected
# later, during checkout, not at signup.
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# Our CustomUser has no 'username' field at all.
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
# 'optional': users can log in immediately after signup; a confirmation
# email is still sent (printed to the console in dev - see EMAIL_BACKEND
# below). Can be switched to 'mandatory' later once real email sending
# (Part 6 deployment) is configured, if email verification is desired.
ACCOUNT_EMAIL_VERIFICATION = 'optional'

# Custom forms (Greek validation messages on password reset page).
ACCOUNT_FORMS = {
    'reset_password_from_key': 'accounts.forms.ResetPasswordKeyForm',
}

# Social login providers (Google / Facebook). Google credentials are read
# from .env (GOOGLE_OAUTH_*). Run `python manage.py setup_oauth` after
# filling .env to sync the SocialApp record for production/admin use.
SOCIALACCOUNT_ADAPTER = "accounts.adapters.KokkorisSocialAccountAdapter"
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Credentials live in the DB SocialApp (sync via `python manage.py setup_oauth`
        # after filling GOOGLE_OAUTH_* in .env). Do not duplicate APPS here — allauth
        # merges DB + settings and raises MultipleObjectsReturned when both exist.
        'provider_class': 'accounts.google_oauth.KokkorisGoogleProvider',
        'SCOPE': ['profile', 'email'],
    },
    'facebook': {
        'APPS': [
            {
                'client_id': 'REPLACE_WITH_FACEBOOK_APP_ID',
                'secret': 'REPLACE_WITH_FACEBOOK_APP_SECRET',
                'key': '',
            }
        ],
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'first_name', 'last_name'],
    },
}

# Where to send users after login/logout.
LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'home'

# Development-only email backend: password reset / email confirmation
# messages are printed to the console instead of actually being sent.
# A real SMTP backend will be configured at deployment time (Part 6).
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@kokkoriseshop.local'

# Google Maps (used by the Part 4 checkout address step: Places Autocomplete
# + interactive map pin for precise delivery location). Maps JavaScript API
# and Places API must be enabled, with billing active, on the Google Cloud
# project this key belongs to. See README.md for setup instructions.
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Google reCAPTCHA v3 — newsletter footer form bot protection.
# Keys live in .env (see .env.example). Create at https://www.google.com/recaptcha/admin
# (type: reCAPTCHA v3). Add localhost + production domain to allowed hosts.
RECAPTCHA_SITE_KEY = os.environ.get("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_ACTION = "newsletter_subscribe"
RECAPTCHA_SCORE_THRESHOLD = 0.5
RECAPTCHA_ENABLED = bool(RECAPTCHA_SITE_KEY and RECAPTCHA_SECRET_KEY)
