"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decimal import Decimal
from urllib.parse import unquote, urlparse

import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local secrets from .env (gitignored). See .env.example for required keys.
# override=True so an edited .env wins over values the runserver autoreloader
# inherited from its parent process — otherwise key changes need a full restart.
load_dotenv(BASE_DIR / ".env", override=True)


def _env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None or not str(raw).strip():
        return default
    return str(raw).strip().lower() in ("true", "1", "yes")


def _env_list(name):
    return [
        item.strip()
        for item in os.environ.get(name, "").split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Local default stays True so runserver keeps working. Set DEBUG=false on the server.
DEBUG = _env_bool("DEBUG", default=True)

_DEFAULT_INSECURE_KEY = (
    "django-insecure-ac3v7p+%56#4x_ds_nw5fyy=igyxg$&2e%ew!#76$!uz0%m^f)"
)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", _DEFAULT_INSECURE_KEY).strip() or (
    _DEFAULT_INSECURE_KEY
)

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")

if not DEBUG:
    if not SECRET_KEY or SECRET_KEY.startswith("django-insecure-"):
        raise ImproperlyConfigured(
            "Set DJANGO_SECRET_KEY to a unique value before running with DEBUG=false."
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "Set ALLOWED_HOSTS (e.g. www.kokkorispetfood.gr,kokkorispetfood.gr) "
            "before running with DEBUG=false."
        )
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # required by allauth

    # Authentication (custom user + social login)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    # Local apps
    'products.apps.ProductsConfig',
    'accounts',
    'orders',
    'cart',
    'checkout',
    'newsletter',
    'wishlist',
    'pages',
    'administration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'core.middleware.BreadcrumbMiddleware',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # Needed for Django admin login and standard email/password auth.
    'django.contrib.auth.backends.ModelBackend',
    # Needed for allauth's own authentication flows (incl. social login).
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'newsletter.context_processors.recaptcha',
                'products.context_processors.nav_state',
                'cart.context_processors.cart_state',
                'accounts.context_processors.auth_helpers',
                'wishlist.context_processors.wishlist_state',
                'core.context_processors.breadcrumbs',
                'core.context_processors.brand',
                'administration.context_processors.administration_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Local default: sqlite. Production: set DATABASE_URL=postgres://...

_DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if _DATABASE_URL:
    _db = urlparse(_DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(_db.path.lstrip("/")),
            "USER": unquote(_db.username or ""),
            "PASSWORD": unquote(_db.password or ""),
            "HOST": _db.hostname or "",
            "PORT": str(_db.port or "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'accounts.password_validators.PasswordHasDigitValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Project-level static files (design assets shared across templates - logos,
# hand-extracted background/design tokens from the site mockup, etc.), as
# opposed to `media/` which holds user/admin-uploaded content (product
# photos). Needed because these files don't belong to any single app.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (user-uploaded content, e.g. product and category images)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model
# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/

AUTH_USER_MODEL = 'accounts.CustomUser'


# django-allauth configuration
# https://docs.allauth.org/en/latest/account/configuration.html

# Log in with email + password only (no separate username field at all).
ACCOUNT_LOGIN_METHODS = {'email'}
# Registration only asks for email + password (entered twice for confirmation).
# All other customer details (phone, city, address, etc.) are collected
# later, during checkout, not at signup.
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# Our CustomUser has no 'username' field at all.
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
# 'optional': users can log in immediately after signup; a confirmation
# email is still sent (printed to the console in dev - see EMAIL_BACKEND
# below). Can be switched to 'mandatory' later once real email sending
# (Part 6 deployment) is configured, if email verification is desired.
ACCOUNT_EMAIL_VERIFICATION = 'optional'

# Custom forms (Greek validation messages on password reset page).
ACCOUNT_FORMS = {
    'reset_password_from_key': 'accounts.forms.ResetPasswordKeyForm',
}

# Social login providers (Google / Facebook). Google credentials are read
# from .env (GOOGLE_OAUTH_*). Run `python manage.py setup_oauth` after
# filling .env to sync the SocialApp record for production/admin use.
SOCIALACCOUNT_ADAPTER = "accounts.adapters.KokkorisSocialAccountAdapter"
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Credentials live in the DB SocialApp (sync via `python manage.py setup_oauth`
        # after filling GOOGLE_OAUTH_* in .env). Do not duplicate APPS here — allauth
        # merges DB + settings and raises MultipleObjectsReturned when both exist.
        'provider_class': 'accounts.google_oauth.KokkorisGoogleProvider',
        'SCOPE': ['profile', 'email'],
    },
    'facebook': {
        'APPS': [
            {
                'client_id': 'REPLACE_WITH_FACEBOOK_APP_ID',
                'secret': 'REPLACE_WITH_FACEBOOK_APP_SECRET',
                'key': '',
            }
        ],
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'first_name', 'last_name'],
    },
}

# Where to send users after login/logout.
LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'home'

# Transactional email (SMTP). Falls back to console when host/user are unset.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "").strip()
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("true", "1", "yes")
BRAND_CONTACT_EMAIL = os.environ.get(
    "BRAND_CONTACT_EMAIL",
    "kokkorisofficial@gmail.com",
).strip()
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    f"Kokkoris Pet Food <{BRAND_CONTACT_EMAIL}>",
).strip()
SERVER_EMAIL = DEFAULT_FROM_EMAIL
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "http://127.0.0.1:8000").strip()

if EMAIL_HOST and EMAIL_HOST_USER:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Google Maps (used by the Part 4 checkout address step: Places Autocomplete
# + interactive map pin for precise delivery location). Maps JavaScript API
# and Places API must be enabled, with billing active, on the Google Cloud
# project this key belongs to. See README.md for setup instructions.
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '').strip()

# -----------------------------------------------------------------------------
# Phone SMS verification (Twilio) — OPTIONAL, disabled by default
# -----------------------------------------------------------------------------
# The shop collects phone as a normal text field (profile/checkout). SMS OTP is
# not required for checkout. Set PHONE_VERIFICATION_ENABLED=true only if you
# later enable Twilio and want login/signup SMS gates:
#   TWILIO_ALPHANUMERIC_SENDER=Kokkoris   (required for Greece; US +1 cannot deliver to +30)
#   TWILIO_ACCOUNT_SID / TWILIO_AUTH_TOKEN
# Run: python manage.py check_twilio
PHONE_VERIFICATION_ENABLED = os.environ.get(
    "PHONE_VERIFICATION_ENABLED", "false"
).lower() in ("true", "1", "yes")

# Twilio SMS (optional — only used when PHONE_VERIFICATION_ENABLED=true)
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "").strip()
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "").strip()
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER", "").strip()
TWILIO_MESSAGING_SERVICE_SID = os.environ.get("TWILIO_MESSAGING_SERVICE_SID", "").strip()
TWILIO_ALPHANUMERIC_SENDER = os.environ.get("TWILIO_ALPHANUMERIC_SENDER", "").strip()

# Google reCAPTCHA v3 — newsletter footer form bot protection.
# Keys live in .env (see .env.example). Create at https://www.google.com/recaptcha/admin
# (type: reCAPTCHA v3). Add localhost + production domain to allowed hosts.
RECAPTCHA_SITE_KEY = os.environ.get("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_ACTION = "newsletter_subscribe"
RECAPTCHA_SCORE_THRESHOLD = 0.5
RECAPTCHA_ENABLED = bool(RECAPTCHA_SITE_KEY and RECAPTCHA_SECRET_KEY)

# -----------------------------------------------------------------------------
# Stripe Payments (one-time card checkout)
# -----------------------------------------------------------------------------
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "").strip()
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "").strip()
STRIPE_CURRENCY = "eur"

# -----------------------------------------------------------------------------
# Box Now locker delivery (Partner API + Map Widget)
# Docs: https://boxnow.gr/en/partner-api
# -----------------------------------------------------------------------------
BOXNOW_PARTNER_ID = os.environ.get("BOXNOW_PARTNER_ID", "").strip()
BOXNOW_OAUTH_CLIENT_ID = os.environ.get("BOXNOW_OAUTH_CLIENT_ID", "").strip()
BOXNOW_OAUTH_CLIENT_SECRET = os.environ.get("BOXNOW_OAUTH_CLIENT_SECRET", "").strip()
BOXNOW_API_URL = os.environ.get(
    "BOXNOW_API_URL", "https://api-stage.boxnow.gr"
).strip().rstrip("/")
BOXNOW_LOCATION_API_URL = os.environ.get(
    "BOXNOW_LOCATION_API_URL", "https://locationapi-stage.boxnow.gr"
).strip().rstrip("/")
BOXNOW_ORIGIN_LOCATION_ID = os.environ.get("BOXNOW_ORIGIN_LOCATION_ID", "").strip()
BOXNOW_NOTIFY_EMAIL = os.environ.get("BOXNOW_NOTIFY_EMAIL", "").strip()
BOXNOW_ORIGIN_CONTACT_NAME = os.environ.get("BOXNOW_ORIGIN_CONTACT_NAME", "").strip()
BOXNOW_ORIGIN_CONTACT_PHONE = os.environ.get("BOXNOW_ORIGIN_CONTACT_PHONE", "").strip()
BOXNOW_ORIGIN_CONTACT_EMAIL = (
    os.environ.get("BOXNOW_ORIGIN_CONTACT_EMAIL", "").strip()
    or BRAND_CONTACT_EMAIL
)
BOXNOW_FEE_SMALL = Decimal(os.environ.get("BOXNOW_FEE_SMALL", "1.80"))
BOXNOW_FEE_MEDIUM = Decimal(os.environ.get("BOXNOW_FEE_MEDIUM", "2.50"))
BOXNOW_FEE_LARGE = Decimal(os.environ.get("BOXNOW_FEE_LARGE", "3.50"))
# Official locker cap (BOX NOW locker-info): 20 kg, Large 36×45×60 cm.
BOXNOW_MAX_WEIGHT_KG = os.environ.get("BOXNOW_MAX_WEIGHT_KG", "20.0")
BOXNOW_WEBHOOK_SECRET = os.environ.get("BOXNOW_WEBHOOK_SECRET", "").strip()
# Map widget needs partnerId. The shipping option itself is always offered.
BOXNOW_WIDGET_ENABLED = bool(BOXNOW_PARTNER_ID)

# -----------------------------------------------------------------------------
# Free shipping promotion (courier + BOX NOW)
# -----------------------------------------------------------------------------
FREE_SHIPPING_ORDER_MINIMUM = Decimal(os.environ.get("FREE_SHIPPING_ORDER_MINIMUM", "60.00"))
# Door-delivery courier fee below the free-shipping threshold (not Box Now).
# Temporary flat rate until a carrier (ACS / Γενική / ΕΛΤΑ, etc.) is chosen.
COURIER_FLAT_FEE = Decimal(os.environ.get("COURIER_FLAT_FEE", "3.20"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "app": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "app",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "kokkoris": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
