# Generated by Django 6.0.6 on 2026-10-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0011_offer_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='offer',
            field=models.ForeignKey(blank=True, help_text='Package offer line (null for normal variant lines).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.offer'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Package size line (null when this row is an offer package).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('offer__isnull', False), ('product_variant__isnull', True)), models.Q(('offer__isnull', True), ('product_variant__isnull', False)), _connector='OR'), name='cartitem_variant_xor_offer'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant__isnull', False)), fields=('cart', 'product_variant'), name='unique_cart_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('offer__isnull', False)), fields=('cart', 'offer'), name='unique_cart_offer'),
        ),
    ]
