# Generated by Django 6.0.6 on 2026-07-05 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_bundle_contents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('special_notes', models.TextField(blank=True, help_text='Optional special comments/instructions about this order.')),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('cash_on_delivery', 'Cash on Delivery')], help_text='How the customer will pay for this order.', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='new', help_text='Where this order currently stands in the payment lifecycle.', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for the order, stored directly so it never changes even if product prices change later.', max_digits=10)),
                ('user', models.ForeignKey(help_text='The customer who placed this order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text="Snapshot of the variant's price at the moment of purchase.", max_digits=8)),
                ('order', models.ForeignKey(help_text='The order this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(help_text='The exact package size/product ordered.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
