# Generated by Django 6.0.6 on 2026-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all order items at the time of purchase, excluding any delivery/courier fee. Stored directly so it never changes even if product prices change later.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Courier delivery fee, computed via checkout.delivery.calculate_courier_fee() at checkout time and snapshotted here. 0 if delivered for free by company staff. Currently always 0 (placeholder) - real per-courier pricing (ACS / ELTA Courier / Geniki Taxydromiki) will be plugged into that single function in a later step, with no changes needed elsewhere.', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_floor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('company_delivery', 'Free delivery by company staff'), ('courier', 'Courier')], default='company_delivery', help_text='Whether this order is delivered for free by company staff or via courier.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_time',
            field=models.CharField(blank=True, default='', help_text="Free text, e.g. 'Τρίτη απόγευμα 5-7'. No real appointment scheduling system yet.", max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='cart_cost + courier_fee - the final amount the customer actually pays.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='new', help_text='Where this order currently stands in the payment/delivery lifecycle.', max_length=10),
        ),
    ]
