# Generated by Django 6.0.6 on 2026-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_amount_order_cart_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_cost',
            field=models.DecimalField(decimal_places=2, help_text='Sum of all order items at the time of purchase, excluding any delivery/courier fee. Stored directly so it never changes even if product prices change later.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('company_delivery', 'Free delivery by company staff'), ('courier', 'Courier')], help_text='Whether this order is delivered for free by company staff or via courier.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, help_text='cart_cost + courier_fee - the final amount the customer actually pays.', max_digits=10),
        ),
    ]
