# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_cancellation_refund_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="boxnow_delivery_request_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Box Now delivery-request id returned by the Partner API.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_locker_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Street address of the selected Box Now locker.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_locker_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Box Now APM locationId selected at checkout.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_locker_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name of the selected Box Now locker.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_locker_postal_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Postal code of the selected Box Now locker.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_parcel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Box Now parcel/voucher id for label printing.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("company_delivery", "Free delivery by company staff"),
                    ("courier", "Courier (ELTA)"),
                    ("box_now", "Box Now locker"),
                ],
                help_text="Whether this order is delivered for free by company staff or via courier.",
                max_length=20,
            ),
        ),
    ]
