# Generated by Django 6.0.6 on 2026-08-31 22:05

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_boxnow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=orders.models._default_order_code, help_text='Public order identifier shown to customers, e.g. KPK4F8A2B1C.', max_length=16, unique=True),
        ),
    ]
