# Generated by Django 6.0.6 on 2026-09-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="boxnow_last_event",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Latest BOX NOW webhook event (use this, not parcelState, for customer copy).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_last_event_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last applied BOX NOW webhook event.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_parcel_pin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pickup PIN from BOX NOW webhooks, when provided.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="boxnow_parcel_state",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Latest BOX NOW parcelState from the Partner API / webhook.",
                max_length=32,
            ),
        ),
    ]
