# Generated by Django 6.0.6 on 2026-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_boxnow_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Courier delivery fee, computed via checkout.delivery.calculate_courier_fee() at checkout time and snapshotted here. 0 if delivered for free by company staff or when the cart qualifies for free shipping. Door courier uses a flat fee (COURIER_FLAT_FEE) until a carrier is chosen.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('company_delivery', 'Free delivery by company staff'), ('courier', 'Courier'), ('box_now', 'Box Now locker')], help_text='Whether this order is delivered for free by company staff or via courier.', max_length=20),
        ),
    ]
