# Generated by Django 6.0.6 on 2026-09-03 12:30

from django.db import migrations, models
from django.db.models import F


def backfill_delivered_collections(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="delivered", delivered_at__isnull=True).update(
        delivered_at=F("order_date")
    )
    Order.objects.filter(
        status="delivered",
        collected_payment_method="",
        payment_method="cash_on_delivery",
    ).update(collected_payment_method="cash_on_delivery")
    Order.objects.filter(
        status="delivered",
        collected_payment_method="",
        payment_method="card",
    ).update(collected_payment_method="card")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_coords_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_payment_method',
            field=models.CharField(blank=True, choices=[('', 'Not collected'), ('card', 'Card'), ('cash_on_delivery', 'Cash')], default='', help_text='Cash or card actually collected at delivery. Empty until the courier declares it, or for prepaid Stripe.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When staff marked this order as delivered.', null=True),
        ),
        migrations.RunPython(backfill_delivered_collections, migrations.RunPython.noop),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_coords_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_payment_method',
            field=models.CharField(blank=True, choices=[('', 'Not collected'), ('card', 'Card'), ('cash_on_delivery', 'Cash')], default='', help_text='Cash or card actually collected at delivery. Empty until the courier declares it, or for prepaid Stripe.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When staff marked this order as delivered.', null=True),
        ),
    ]
