# Generated by Django 6.0.6 on 2026-07-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Animal name, e.g. 'Dog', 'Cat'.", max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier, auto-generated from the name.', max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Animal Type',
                'verbose_name_plural': 'Animal Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name, e.g. 'Dry Food'.", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier, auto-generated from the name.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Brand/manufacturer name, e.g. 'OWNAT'.", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short unique code for the company, e.g. 'OWN'.", max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional brand logo image.', null=True, upload_to='companies/logos/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name, e.g. 'OWNAT Adult Medium'.", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier, auto-generated from the name.', max_length=220, unique=True)),
                ('components', models.TextField(blank=True, help_text='Ingredients/composition list. Shared across all package sizes.')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is currently available for sale.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(help_text='The target animal for this product.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.animaltype')),
                ('category', models.ForeignKey(help_text='The category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('company', models.ForeignKey(help_text='The brand/manufacturer of this product.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.company')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Package size as a number (e.g. 2, 10, 15). Unit is inferred from category.', max_digits=6)),
                ('sku', models.CharField(blank=True, help_text='Optional unique stock-keeping unit code for this specific variant.', max_length=50, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this specific package size.', max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of units currently available for this package size.')),
                ('product', models.ForeignKey(help_text='The parent product this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'weight'],
                'constraints': [models.UniqueConstraint(fields=('product', 'weight'), name='unique_product_weight')],
            },
        ),
    ]
