# Generated by Django 6.0.6 on 2026-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_contents',
            field=models.TextField(blank=True, help_text="For 'Bundle' category products only: a short, Latin-character summary of what individual items/flavors are mixed inside this pack, e.g. '2x Chicken in Gravy, 2x Salmon in Jelly'."),
        ),
    ]
