# Generated by Django 6.0.6 on 2026-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_bundle_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='availability',
            field=models.CharField(choices=[('available_now', 'Immediately Available'), ('on_order', 'On Order (special order from supplier)'), ('out_of_stock', 'Out of Stock')], default='available_now', help_text="Set manually by staff - NOT derived automatically from 'stock'. Used to tell the customer whether this ships from current shop stock right away, or needs to be specially ordered from the supplier first (which implies a delivery delay).", max_length=20),
        ),
    ]
