# Generated by Django 6.0.6 on 2026-07-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=20, help_text='Number of units currently available for this package size.'),
        ),
    ]
