# Generated by Django 6.0.6 on 2026-07-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_stock_default_20'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Package height in centimetres (cm) for volumetric weight.', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Package length in centimetres (cm) for volumetric weight.', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping weight in kilograms (kg) for courier billing.', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Package width in centimetres (cm) for volumetric weight.', max_digits=6),
        ),
    ]
