# Generated by Django 6.0.6 on 2026-10-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_favourite_score_20_4_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price paid by the customer (rounded up to 0.10 €).', max_digits=8)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Auto-computed from regular total vs package price.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for this specific package size (stored rounded up to the next 0.10 €).', max_digits=8),
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.offer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Offer item',
                'verbose_name_plural': 'Offer items',
                'constraints': [models.UniqueConstraint(fields=('offer', 'variant'), name='unique_offer_variant')],
            },
        ),
    ]
