# Generated by Django 6.0.6 on 2026-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_offer_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, help_text='Required for multi-product packages. Single-item offers use the product name.', max_length=200),
        ),
    ]
